### ISSUE TITLE
external.py can crash the badge

### ISSUE THREAD

**Issue by sammachin** [emfcamp/Mk3-Firmware#63] opened 2016-08-03 07:26 UTC
If something in   an external.py fails (for example the HTTP request  because you stopped the server!) the whole badge seems to crash as soon as you reboot and you can't get out of it.

```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "apps/home/main.py", line 282, in <module>
  File "apps/messages/external.py", line 15, in periodic_home
  File "/flash/lib/http_client.py", line 223, in get
  File "/flash/lib/http_client.py", line 179, in request
  File "/flash/lib/http_client.py", line 155, in open_http_socket
OSError: -1
```

Would be good if we can wrap the calls to external.py in some kind of try loop
I've put a try in my code now which should work but would be better to protect the homescreen itself from bad code

**Comment by thinkl33t** [comment] 2016-08-03 08:23
The API for running background tasks has changed slightly, you need to add needs_network=True (I think) to the external.py if your app needs the network to be up.

Have a look at logger.py for an example of how this works now.

**Comment by thinkl33t** [comment] 2016-08-03 10:40
This is a duplicate of #47 I think - closing for now.

**Closed by thinkl33t** 2016-08-03 10:40 UTC
